"""Fit active-city fire attachments to indexed original vessel openings, not sprite centres."""
from pathlib import Path
import hashlib, json, math, struct

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
ORIGINAL=ROOT.parents[1]/'active/jak3/data/decompiler_out/jak3/levels'

def rotate(q,p):
    x,y,z,w=q; a,b,c=p
    tx=2*(y*c-z*b);ty=2*(z*a-x*c);tz=2*(x*b-y*a)
    return [a+w*tx+y*tz-z*ty,b+w*ty+z*tx-x*tz,c+w*tz+x*ty-y*tx]

def vertices(path):
    raw=path.read_bytes();n=struct.unpack_from('<I',raw,12)[0]
    doc=json.loads(raw[20:20+n]);base=28+n;points=set()
    for mesh in doc['meshes']:
      for p in mesh['primitives']:
        if doc['materials'][p['material']].get('name')!='wascity-metal-door-01':continue
        a=doc['accessors'][p['attributes']['POSITION']];v=doc['bufferViews'][a['bufferView']]
        off=base+v.get('byteOffset',0)+a.get('byteOffset',0)
        ia=doc['accessors'][p['indices']];iv=doc['bufferViews'][ia['bufferView']]
        io=base+iv.get('byteOffset',0)+ia.get('byteOffset',0)
        kind={5125:'I',5123:'H',5121:'B'}[ia['componentType']];stride=iv.get('byteStride',struct.calcsize('<'+kind))
        indices={struct.unpack_from('<'+kind,raw,io+i*stride)[0]for i in range(ia['count'])}
        for i in indices:points.add(struct.unpack_from('<3f',raw,off+i*v.get('byteStride',12)))
    return points

def main():
    inventory=ROOT/'city-remaster/inventory.json'
    actors=[a for a in json.loads(inventory.read_text())['source_actor_fire_candidates_all_maps']
            if a['level']in('wascitya','wascityb')and a['art_name']in('group-waswide-gaslamp','group-waswide-talltorch')]
    assert len(actors)==61
    fits=[];sources=[]
    for level in ('wascitya','wascityb'):
      path=ORIGINAL/level/(level+'-background.glb');points=vertices(path)
      sources.append({'path':str(path),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
      for actor in [a for a in actors if a['level']==level]:
        p=actor['trans_m'];q=actor['quat'];qi=[-q[0],-q[1],-q[2],q[3]]
        candidates=[]
        for v in points:
          if sum((v[i]-p[i])**2 for i in range(3))>2.5**2:continue
          local=rotate(qi,[v[i]-p[i]for i in range(3)])
          if actor['art_name']=='group-waswide-gaslamp':
            if math.hypot(*local[:2])<1.2 and -1.8<local[2]<.15:candidates.append((local,v))
          elif math.hypot(*local[:2])<.4 and -.2<local[2]<.2:candidates.append((local,v))
        assert len(candidates)>=6,(level,actor['aid'],len(candidates))
        if actor['art_name']=='group-waswide-gaslamp':
          ring=sorted(candidates,key=lambda x:x[0][2],reverse=True)[:6]
          assert max(x[0][2]for x in ring)-min(x[0][2]for x in ring)<.22,(actor['aid'],'non-ring')
        else: ring=[x for x in candidates if math.hypot(*x[0][:2])>.12]
        centre=[sum(x[0][i]for x in ring)/len(ring)for i in range(2)]
        radial=[math.hypot(x[0][0]-centre[0],x[0][1]-centre[1])for x in ring]
        assert max(radial)/min(radial)<1.6,(actor['aid'],'eccentric opening',radial)
        # Start below the lowest rim. Opaque native metal clips the lower volume;
        # the narrow footprint prevents the base from escaping through the sides.
        offset=[centre[0],centre[1],min(x[0][2]for x in ring)-.075]
        footprint=min(radial)*.85
        tall=actor['art_name']=='group-waswide-talltorch'
        radius=.45 if tall else max(.70,footprint*1.12)
        height=4.4 if tall else 4.0
        world_delta=rotate(q,offset)
        fits.append({**actor,'region':1 if level=='wascitya'else 2,
          'opening_vertices':len(ring),'opening_world_vertices':[x[1]for x in ring],
          'offset_local_m':offset,'fuel_world_m':[p[i]+world_delta[i]for i in range(3)],
          'footprint_m':footprint,'radius_m':radius,'height_m':height,
          'method':'indexed native vessel rim; inset 7.5 cm, radius 85% of inscribed opening'})
    report={'sources':sources,'inventory_sha256':hashlib.sha256(inventory.read_bytes()).hexdigest(),'fits':fits}
    (HERE/'source-fit.json').write_text(json.dumps(report,indent=2)+'\n')
    lines=['// Generated by city-fire-v2/fit_sources.py; source actor + indexed vessel opening.',
           'inline constexpr std::array<Attachment, 61> attachments{{']
    for a in fits:
      vals=','.join(f'{v:.8f}f'for v in a['offset_local_m'])
      lines.append(f"  {{{a['region']}, {a['aid']}, {{{vals}}}, {a['radius_m']:.8f}f, {a['height_m']:.8f}f, {a['footprint_m']:.8f}f}},")
    lines+=['}};','']
    (HERE/'CityFireAttachments.inc').write_text('\n'.join(lines))
    print('Fitted',len(fits),'native openings; height range',min(a['fuel_world_m'][1]-a['trans_m'][1]for a in fits),max(a['fuel_world_m'][1]-a['trans_m'][1]for a in fits))

if __name__=='__main__':main()
