"""Derive the renderer's shoreline mask from Jak 3's native ocean lookup tables."""
from pathlib import Path
import hashlib,json,re

ROOT=Path(__file__).resolve().parent.parent
SOURCE=ROOT/'data/goal_src/jak3/levels/wascity/wascity-ocean.gc'
TARGET=ROOT/'engine-src/game/graphics/opengl_renderer/ocean/OceanCoastMask.h'

def form(text,start):
    depth=0
    for i in range(start,len(text)):
        if text[i]=='(':depth+=1
        elif text[i]==')':
            depth-=1
            if depth==0:return text[start:i+1]
    raise ValueError('Unbalanced source form')

def forms(text,kind):
    return [form(text,m.start()) for m in re.finditer(r"\(new 'static '"+kind+r'(?=[\s)])',text)]

def number(value):return int(value[2:],16) if value.startswith('#x') else int(value)
def array(item,kind,count):
    found=re.search(r"\(new 'static 'array "+kind+r' '+str(count)+r'\s+([^)]*)\)',item)
    values=[number(v) for v in found[1].split()] if found else [0]*count
    assert len(values)==count
    return values

def main():
    text=SOURCE.read_text()
    trans=[]
    for item in forms(text,'ocean-trans-index'):
        fields={k:number(v) for k,v in re.findall(r':(parent|child)\s+(#x[0-9a-f]+|-?\d+)',item)}
        trans.append((fields.get('parent',0),fields.get('child',0)))
    near=[array(i,'uint16',16) for i in forms(text,'ocean-near-index')]
    masks=[array(i,'uint8',8) for i in forms(text,'ocean-mid-mask')]
    assert (len(trans),len(near),len(masks))==(2304,189,544)
    origin=(-256.,-2762.)
    def wet(x,z):
        x-=origin[0];z-=origin[1]
        if x<0 or z<0 or x>=4608 or z>=4608:return True
        ix,iz=int(x/3),int(z/3)
        parent,child=trans[(iz//32)*48+ix//32]
        if parent in (-1,65535):return False
        m=near[child][((iz//8)&3)*4+((ix//8)&3)]
        return m!=65535 and not (masks[m][iz&7] & (1<<(ix&7)))
    observations=[{'name':name,'xz':[x,z],'wet':wet(x,z)} for name,x,z in (
        ('WCA reported flooded street',2240.2834,-40.7634),
        ('native coastal breaker anchor',1484.849,-528.791),
        ('swimming test position',1647.,-430.),
        ('market raised terrain above sea level',1767.073,-330.502))]
    assert not observations[0]['wet'], 'Reported WCA road must be outside the native ocean'
    assert observations[1]['wet'], 'Coastal breaker must remain inside native ocean'
    assert observations[2]['wet'], 'Accepted swimming test position must remain inside native ocean'
    def emit(name,typ,rows):
        width=len(rows[0])
        return f'  inline static constexpr {typ} {name}[{len(rows)}][{width}] = {{\n'+''.join('    {'+','.join(str(v) for v in row)+'},\n' for row in rows)+'  };\n'
    header='''#pragma once
#include <cstdint>

// Generated by models-v2/build_ocean_coast_mask.py from the native Spargus
// ocean tables. Matches ocean.gc::get-height: 96m -> 24m -> 3m cells;
// a SET mask bit is dry. Keep the original holes under roads and buildings.
class OceanCoastMask {
 public:
  static constexpr int SIZE = 1536;
  static constexpr float ORIGIN_X = -256.f;
  static constexpr float ORIGIN_Z = -2762.f;
  static bool cell(int x, int z) {
    // The original far-ocean surrounds the finite native map.
    if (x < 0 || z < 0 || x >= SIZE || z >= SIZE) return true;
    const auto* transition = transitions[(z / 32) * 48 + x / 32];
    if (transition[0] < 0) return false;
    const auto mask = near_indices[transition[1]][((z / 8) & 3) * 4 + ((x / 8) & 3)];
    return mask != 65535 && !(masks[mask][z & 7] & (1 << (x & 7)));
  }
  static bool contains(float x, float z) {
    x -= ORIGIN_X; z -= ORIGIN_Z;
    if (x < 0.f || z < 0.f || x >= SIZE * 3.f || z >= SIZE * 3.f) return true;
    return cell(int(x / 3.f), int(z / 3.f));
  }
 private:
'''
    header+=emit('transitions','int16_t',trans)+emit('near_indices','uint16_t',near)+emit('masks','uint8_t',masks)+'};\n'
    TARGET.write_text(header)
    report={'source':str(SOURCE),'source_sha256':hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        'header':str(TARGET),'header_sha256':hashlib.sha256(TARGET.read_bytes()).hexdigest(),
        'origin_xz':origin,'grid_size':1536,'cell_metres':3,'lookup':'Native transition / near / inverted mid-mask bit',
        'observations':observations,'water_cells':sum(wet(origin[0]+x*3+1.5,origin[1]+z*3+1.5) for z in range(1536) for x in range(1536))}
    (ROOT/'models-v2/ocean-coast-mask-report.json').write_text(json.dumps(report,indent=2))
    print(json.dumps(report,indent=2))

if __name__=='__main__':main()
